const product = {
  "kitchen scale": {
    name: "10kg/1g",
    "Brand Name": "",
    Type: "ছোট ওজন মাপার যন্ত্র",
    Wheel: "না",
    Price: 650,
    Specification: [],
    Category: "কিচেন স্কেল",
    "Picture Path": "./images/kitchen/main.jpg",
    "number sold": 10,
    "other pic path": [
      "./images/kitchen/1.jpg",
      "./images/kitchen/2.jpg",
      "./images/kitchen/3.jpg",
    ],
  },

  "body scale": {
    name: "Body Scale",
    "Brand Name": "",
    Type: "ডিজিটাল ওজন মাপার যন্ত্র ",
    Wheel: "না",
    Price: 1000,
    Specification: [
      "উপাদান: টেম্পার্ড গ্লাস & প্লাস্টিক",
      "ফাংশন: ওজন পরিমাপ, BMI ফাংশনসহ, ব্লুটুথ সংযোগ",
      "একক: কেজি / পাউন্ড",
      "ব্যাটারি: 2*AAA শুকনো ব্যাটারি",
      "ক্ষমতা: 180kg/50g",
      "স্কেলের আকার: 26*26*2.3 cm",
      "ডিসপ্লে: LCD",
      "মোট ওজন : 15kg",
    ],
    Category: "বডি স্কেল",
    "Picture Path": "./images/bodyscale/main.jpg",
    "number sold": 12,
    "other pic path": [
      "./images/bodyscale/1.jpg",
      "./images/bodyscale/2.jpg",
      "./images/bodyscale/3.jpg",
    ],
  },

  "20kg/1g": {
    name: "20kg/1g",
    "Brand Name": "GRAMEEN ROCKET",
    Type: "",
    Wheel: "না",

    Price: 2050,
    Specification: [
      "battery 4v 4AH, net weight 450g",
      "transformer charging system",
      "pan: 30*30.5 cm",
      "display:both side with bigger Digit, higher brightness",
      "body made of refined fibre",
      "plate weight is 360g",
      "plate can be both T-plate or Plain-plate",
      "color can be yellow or orange",
    ],
    Category: "Kitchen Scale",
    "Picture Path": "./images/20-30kg/main.PNG",
    "number sold": 0,
    "other pic path": ["./images/20-30kg/10kg.PNG"],
 
  },

  "30kg/1g": {
    name: "30kg/1g",
    "Brand Name": "GRAMEEN ROCKE",
    Type: "",
    Wheel: "না",

    Price: 2100,
    Specification: [
      "battery 4v 4AH, net weight 450g",
      "transformer charging system",
      "pan: 30*30.5 cm",
      "display:both side with bigger Digit, higher brightness",
      "body made of refined fibre",
      "plate weight is 360g",
      "plate can be both T-plate or Plain-plate",
      "color can be yellow or orange",
    ],
    Category: "Kitchen Scale",
    "Picture Path": "./images/20-30kg/main.PNG",
    "number sold": 0,
    "other pic path": ["./images/20-30kg/10kg.PNG"],
  },

  "40kg/1g": {
    name: "40kg/1g",
    "Brand Name": "topstar*",
    Type: "",
    Wheel: "না",
    Price: 2350,
    Specification: [
      "উপাদান: প্লাস্টিক, SS কি-প্যাড, সমতল প্লেট, প্লেটের ওজন 420g, প্লাস্টিক ফিট লক",
      "ফাংশন: ওজন পরিমাপ, মূল্য গণনা",
      "একক: কেজি / গ্রাম",
      "ব্যাটারি: 4V/4Ah (420g) লিড-অ্যাসিড ব্যাটারি লক সিস্টেম সহ",
      "ক্ষমতা: 40kg/1g",
      "স্কেলের আকার: 33*33*12.5 cm",
      "ডিসপ্লে: সবুজ LED",
      "মোট ওজন: 15.5kg",
      "কোনো হ্যান্ডেল নেই",
    ],
    Category: "কিচেন স্কেল",
    "Picture Path": "./images/40kg/main.png",
    "number sold": 0,
    "other pic path": [
      "./images/40kg/1.jpg",
      "./images/40kg/2.png",
      "./images/40kg/3.jpg",
    ],
  },

  "60kg/5g": {
    name: "60kg/5g",
    "Brand Name": "topstar*",
    Type: "",
    Wheel: "না",
    Price: 3300,
    Specification: [
      "৬০ কেজি প্ল্যাটফর্ম স্কেল",
      "আকার: 30*34cm",
      "ব্যাটারি: 4V 4Ah 450g",
      "স্টিল কি-প্যাড,  ডিজিটাল ডুয়াল ডিসপ্লে",
      "স্টেইনলেস স্টিল প্লেট",
      "১৮০ কেজি সেন্সর প্যাকেজ",
      "রঙ: সিলভার",
      "বড় আকারের স্কেল ফুট",
      "মোট ওজন: 23.2kg",
      "কালো রঙের ফুট",
    ],
    Category: "বেঞ্চ স্কেল",
    "Picture Path": "./images/60kg/main.png",
    "number sold": 0,
    "other pic path": ["./images/60kg/1.png", "./images/60kg/2.png"],
  },

  "100kg/5g": {
    name: "100kg/5g",
    "Brand Name": "GRAMEEN ROCKET",
    Type: "SS",
    Wheel: "না",
    Price: 3700,
    Specification: [
      "উপাদান: লোহা স্ট্যান্ড, এসএস প্যান, এসএস কিপ্যাড ডিসপ্লে, বেড়া",
      "এসএস প্যান আকার: ৩০*৪০ সেমি",
      "ধারণক্ষমতা: ১০০ কেজি/১০ গ্রাম, এলইডি ডুয়াল ডিসপ্লে",
      "ব্যাটারি: 4V 4Ah ৪২০ গ্রাম, তিন-পিন চার্জ",
      "প্রেস বোতাম: ৩০০,০০০ বার থেকে বেশি",
      "ওজন:  ৯.১ কেজি",
    ],
    Category: "বেঞ্চ স্কেল",
    "Picture Path": "./images/99kg/main.png",
    "number sold": 100,
    "other pic path": ["./images/99kg/1.png", "./images/99kg/2.png"],
  },

  "100kg/10gMS": {
    name: "100kg/10g MS",
    "Brand Name": "GRAMEEN ROCKET",
    Type: "MS",
    Wheel: "না",

    Price: 4400,
    Specification: [
      "Bright display with bigger digit",
      "Product has rail",
      "Size 35 * 45 cm",
      "4V 4Ah 450g battery",
      "Monitor / Indicator has steel keypad",

    ],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/100kgms/main.png",
    "number sold": 120,
    "other pic path": ["./images/100kgms/1.png"],
  },

  "100kg/10gSS": {
    name: "100kg/10g SS",
    "Brand Name": "GRAMEEN ROCKET",
    Type: "SS",
    Wheel: "না",
    Price: 4550,
    Specification: [
      "মনিটরের সামনের এবং পিছনের ডিসপ্লে",
      "১০০ কেজি/১০ গ্রাম প্ল্যাটফর্ম স্কেল রেল এবং পা সহ",
      "আকার: ৩৫*৪৫ সেমি",
      "রঙ - এসএস রঙ যেমন ছবি",
      "২০০ কেজি ধারণক্ষমতা লোড সেল কভার সহ",
      "4V 4Ah ৪৫০গ্রাম ব্যাটারি",
      "স্টিল কিপ্যাড",
      "*২০০ কেজি সেন্সর প্যাকেজ",
      "ওজন: ১৩ কেজি",
    ],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/100kgss/main.png",
    "number sold": 120,
    "other pic path": ["./images/100kgss/1.png", "./images/100kgss/2.png"],
  },

  "150kg/10gMS": {
    name: "150kg/10g MS",
    "Brand Name": "",
    Type: "MS",
    Wheel: "না",
    Price: 4800,
    Specification: [],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/150kgms/main.png",
    "number sold": 10,
    "other pic path": ["./images/150kgms/1.png", "./images/150kgms/2.png"],
  },
  "150kg/10gSS": {
    name: "150kg/10g SS",
    "Brand Name": "",
    Type: "SS",
    Wheel: "না",
    Price: 5000,
    Specification: [],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/150kgss/main.png",
    "number sold": 10000,
    "other pic path": ["./images/150kgss/1.png", "./images/150kgss/2.png"],
  },

  "250kg/20gMS": {
    name: "250kg/20g MS",
    "Brand Name": "",
    Type: "MS",
    Wheel: "না",
    Price: 6500,
    Specification: [],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/250kgms/main.png",
    "number sold": 10,
    "other pic path": ["./images/250kgms/1.png", "./images/250kgms/2.png"],
  },
  "250kg/20gSS": {
    name: "250kg/20g SS",
    "Brand Name": "",
    Type: "SS",
    Wheel: "না",
    Price: 7200,
    Specification: [],
    Category: "প্ল্যাটফর্ম স্কেল",

    "Picture Path": "./images/250kgss/main.png",
    "number sold": 8000,
    "other pic path": ["./images/250kgss/1.png"],

  },

  "300kg/20gMS": {
    name: "300kg/20g MS",
    "Brand Name": "GRAMEEN ROCKET",
    Type: "MS",
    Wheel: "হ্যাঁ",
    Price: 7200,
    Specification: [
      "৩০০ কেজি প্ল্যাটফর্ম স্কেল",
      "আকার: ৪৫*৬০ সেমি",
      "4V 4Ah ৪৫০গ্রাম ব্যাটারি",
      "স্টিল কিপ্যাড ডিজিটাল ডুয়াল ডিসপ্লে",
      "ওজন পরিমাপ প্যানের পুরুত্ব ১.৮ মিমি",
      "বেড়ার উচ্চতা ৬৫ সেমি",
      "মাথার উচ্চতা ৯১ সেমি",
      "৮০০ কেজি সেন্সর প্যাকেজ",
      "*চাকা সহ",
      "ওজন: ২৬ কেজি",
    ],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/300kgms/main.png",
    "number sold": 1000,
    "other pic path": [
      "./images/300kgms/1.png",
      "./images/300kgms/2.png",
      "./images/300kgms/3.png",
    ],
  },

  "300kg/20gSS": {
    name: "300kg/20g SS",
    "Brand Name": "GRAMEEN ROCKET",
    Type: "MS",
    Wheel: "হ্যাঁ",
    Price: 8000,
    Specification: [
      "*৩০০ কেজি প্ল্যাটফর্ম স্কেল",
      "*আকার: ৪৫*৬০ সেমি",
      "*৪ভি ৪এ ৪৫০গ্রাম ব্যাটারি",
      "*স্টিল কিপ্যাড ডিজিটাল ডুয়াল ডিসপ্লে",
      "*ওজন পরিমাপ প্যানের পুরুত্ব ১.৮ মিমি",
      "*আই-আকৃতির বেড়ার উচ্চতা ৬৫ সেমি",
      "*মাথার উচ্চতা ৯১ সেমি",
      "*৮০০ কেজি সেন্সর প্যাকেজ",
      "*রঙিন ছবি মডেল",
      "*চাকা সহ",
      "আকার: ৯৯*৪৬*২৩.৫ সেমি",
      "গ্রস ওজন/নেট ওজন: ২৬ কেজি/২৫ কেজি",
    ],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/300kgss/main.png",
    "number sold": 1000,
    "other pic path": ["./images/300kgss/main.png"],
  },

  "500kg/50gMS": {
    name: "500kg/50g MS",
    "Brand Name": "",
    Type: "MS",
    Wheel: "হ্যাঁ",
    Price: 8500,
    Specification: [],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/500kgms/main.png",
    "number sold": 10,
    "other pic path": [
      "./images/500kgms/1.png",
      "./images/500kgms/2.png",
      "./images/500kgms/3.png",
    ],
  },
  "500kg/50gSS": {
    name: "500kg/50g SS",
    "Brand Name": "",
    Type: "SS",
    Wheel: "হ্যাঁ",
    Price: 8000,
    Specification: [],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/500kgss/main.png",
    "number sold": 10,
    "other pic path": [
      "./images/500kgss/1.png",
      "./images/500kgss/2.png",
      "./images/500kgss/3.png",
    ],
  },
};
