const product = {
  "kitchen scale": {
    name: "10kg/1g",
    "Brand Name": "",
    Type: "",
    Wheel: "না",
    Price: 10.6,
    Specification: [],
    Category: "কিচেন স্কেল",
    "Picture Path": "./images/kitchen/main.jpg",
    "number sold": 10,
    "other pic path": [
      "./images/kitchen/1.jpg",
      "./images/kitchen/2.jpg",
      "./images/kitchen/3.jpg",
    ],
  },

  "body scale": {
    name: "Body Scale",
    "Brand Name": "",
    Type: "",
    Wheel: "না",
    Price: 2.71,
    Specification: [
      "উপাদান: টেম্পার্ড গ্লাস + প্লাস্টিক",
      "ফাংশন: ওজন পরিমাপ, BMI ফাংশনসহ, ব্লুটুথ সংযোগ",
      "একক: কেজি / পাউন্ড",
      "ব্যাটারি: 2*AAA শুকনো ব্যাটারি",
      "ক্ষমতা: 180kg/50g",
      "স্কেলের আকার: 26*26*2.3 cm",
      "ডিসপ্লে: LCD",
      "প্যাকিং: ১০ পিস / কার্টন",
      "মাত্রা: 58*35*36 cm",
      "মোট ওজন / নিট ওজন: 15kg / 14kg",
    ],
    Category: "বডি স্কেল",
    "Picture Path": "./images/bodyscale/main.jpg",
    "number sold": 12,
    "other pic path": [
      "./images/bodyscale/1.jpg",
      "./images/bodyscale/2.jpg",
      "./images/bodyscale/3.jpg",
    ],
  },

  "20kg/1g": {
    name: "20kg/1g",
    "Brand Name": "",
    Type: "",
    Wheel: "না",
    Price: 10.6,
    Specification: [],
    Category: "",
    "Picture Path": "./images/kitchen/main.jpg",
    "number sold": 0,
    "other pic path": [
      "./images/kitchen/1.jpg",
      "./images/kitchen/2.jpg",
      "./images/kitchen/3.jpg",
    ],
  },

  "30kg/1g": {
    name: "30kg/1g",
    "Brand Name": "",
    Type: "",
    Wheel: "না",
    Price: 10.6,
    Specification: [],
    Category: "",
    "Picture Path": "./images/kitchen/main.jpg",
    "number sold": 0,
    "other pic path": [
      "./images/kitchen/1.jpg",
      "./images/kitchen/2.jpg",
      "./images/kitchen/3.jpg",
    ],
  },

  "40kg/1g": {
    name: "40kg/1g",
    "Brand Name": "topstar*",
    Type: "",
    Wheel: "না",
    Price: 13,
    Specification: [
      "উপাদান: প্লাস্টিক + SS কি-প্যাড + সমতল প্লেট, প্লেটের ওজন 420g, প্লাস্টিক ফিট লক",
      "ফাংশন: ওজন পরিমাপ, মূল্য গণনা",
      "একক: কেজি / গ্রাম",
      "রঙ: কাস্টমাইজড",
      "ব্যাটারি: 4V/4A (420g) লিড-অ্যাসিড ব্যাটারি লক সিস্টেম সহ",
      "ক্ষমতা: 40kg/1g",
      "লোডসেল: 88mm",
      "মাদারবোর্ড: কাস্টমাইজড ক্যালিব্রেশন কোড করা যাবে",
      "স্কেলের আকার: 33*33*12.5 cm",
      "ডিসপ্লে: সবুজ LED",
      "লোডসেল স্ট্যান্ড: 工 আই-আকৃতির কাঠামো",
      "প্যাকিং: ৫ পিস / কার্টন",
      "মাত্রা: 65*39.5*37.5 cm",
      "মোট ওজন / নিট ওজন: 15.5kg / 14kg",
      "কোনো হ্যান্ডেল নেই",
      "একই ব্র্যান্ড নাম থাকবে",
      "রঙিন কার্টুন ডিজাইন পরে ইমেইলে প্রদান করা হবে",
    ],
    Category: "কিচেন স্কেল",
    "Picture Path": "./images/40kg/main.png",
    "number sold": 0,
    "other pic path": [
      "./images/40kg/1.jpg",
      "./images/40kg/2.png",
      "./images/40kg/3.jpg",
    ],
  },

  "60kg/5g": {
    name: "60kg/5g",
    "Brand Name": "topstar*",
    Type: "",
    Wheel: "না",
    Price: 18.5,
    Specification: [
      "৬০ কেজি প্ল্যাটফর্ম স্কেল, ৪টি পিস এক মাস্টার কার্টনে",
      "আকার: 30*34cm",
      "ব্যাটারি: 4V 4A 450g",
      "স্টিল কী ডিজিটাল ডুয়াল ডিসপ্লে",
      "স্টেইনলেস স্টিল প্লেট",
      "১৮০ কেজি সেন্সর প্যাকেজ",
      "রঙ: সিলভার",
      "বড় আকারের স্কেল ফুট",
      "মাত্রা: 58*32.5*68cm",
      "মোট ওজন / নিট ওজন: 23.2kg / 20.8kg",
      "এক মাস্টার কার্টনে ৪টি পিস থাকবে",
      "বডির ছিদ্র প্লাস্টিক কভার দিয়ে ঢেকে দিতে হবে",
      "কালো রঙের ফুট ব্যবহার করতে হবে",
      "মনিটর স্ট্যান্ডের প্ল্যাটফর্ম স্কেলে অবশ্যই একটি লোগো লিখতে হবে",
    ],
    Category: "বেঞ্চ স্কেল",
    "Picture Path": "./images/60kg/main.png",
    "number sold": 0,
    "other pic path": [
      "./images/60kg/1.png",
      "./images/60kg/2.png",
    ],
  },

  "100kg/5g": {
    name: "100kg/5g",
    "Brand Name": "GRAMEEN ROCKET",
    Type: "SS",
    Wheel: "না",
    Price: 10,
    Specification: [
      "উপাদান: লোহা স্ট্যান্ড + এসএস প্যান + এসএস কিপ্যাড ডিসপ্লে + বেড়া",
      "এসএস প্যান আকার: ৩০*৪০ সেমি",
      "ধারণক্ষমতা: ১০০ কেজি/১০ গ্রাম, এলইডি ডুয়াল ডিসপ্লে",
      "২০০ কেজি বড় লোড সেল কভারের সঙ্গে",
      "ব্যাটারি: ৪ভি ৪এ ৪২০ গ্রাম, তিন-পিন চার্জ, এসি ১১০ভি থেকে ২৪০ভি, ৯৯ বার একসুমুলেশন",
      "প্রেস বোতাম: ৩০০,০০০ বার থেকে বেশি",
      "মাদার বোর্ড: ডাবল এপোক্সি বোর্ড",
      "ডিসপ্লে এবং কিপ্যাড: এপোক্সি বোর্ড",
      "প্যাকিং: ৭০*৩১.৫*১৬ সেমি/১ পিসি",
      "গ্রস ওজন/নেট ওজন: ৯.২২ কেজি/ ৯.১ কেজি",
      "নাম: গ্রামীণ রকেট",
    ],
    Category: "বেঞ্চ স্কেল",
    "Picture Path": "./images/99kg/main.png",
    "number sold": 100,
    "other pic path": [
      "./images/99kg/1.png",
      "./images/99kg/2.png",
    ],
  },

  "100kg/10gMS": {
    name: "100kg/10g MS",
    "Brand Name": "",
    Type: "MS",
    Wheel: "না",
    Price: 23,
    Specification: [],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/40kg/main.png",
    "number sold": 0,
    "other pic path": [
      "./images/100kgms/1.jpg",
      "./images/100kgms/2.jpg",
      "./images/100kgms/3.jpg",
    ],
  },

  "100kg/10gSS": {
    name: "100kg/10g SS",
    "Brand Name": "GRAMEEN ROCKET",
    Type: "SS",
    Wheel: "না",
    Price: 10,
    Specification: [
      "মনিটরের সামনের এবং পিছনের ডিসপ্লের উজ্জ্বলতা একই হওয়া উচিত।",
      "*১০০ কেজি/১০ গ্রাম প্ল্যাটফর্ম স্কেল রেল এবং পা সহ",
      "*আকার: ৩৫*৪৫ সেমি",
      "*রঙ - এসএস রঙ যেমন ছবি, কালো রাবার",
      "*২০০ কেজি ধারণক্ষমতা লোড সেল কভার সহ",
      "*৪ভি ৪এহ ৪৫০গ্রাম ব্যাটারি .৩ ক্যাবল",
      "*মনিটর / ইনডিকেটর: যেমনটি আমি আপনাকে কিনেছিলাম, স্টিল কিপ্যাড",
      "*ওজন পরিমাপ প্যান: (যেমন ৪০ X ৫০ সাইজের এসএস পণ্য, পা সহ যা আমি আপনাকে কিনেছিলাম)",
      "*২০০ কেজি সেন্সর প্যাকেজ",
      "*মেইন বোর্ড: ক্যালিব্রেশন কোড (যেমন ৪০ X ৫০ সাইজের এসএস পণ্য, পা সহ যা আমি আপনাকে কিনেছিলাম)",
      "গ্রস ওজন/নেট ওজন: ১২ কেজি/১৩ কেজি",
      "ব্র্যান্ড নাম: গ্রামীণ রকেট",
      "নীল মার্ক করা স্থানে জাপান স্ট্যান্ডার্ড লিখতে হবে",
    ],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/100kgss/main.png",
    "number sold": 120,
    "other pic path": [
      "./images/100kgss/1.png",
      "./images/100kgss/2.png",
    ],
  },

  "150kg/10gMS": {
    name: "100kg/10g MS",
    "Brand Name": "",
    Type: "MS",
    Wheel: "না",
    Price: 10,
    Specification: [],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/40kg/main.png",
    "number sold": 10,
    "other pic path": [
      "./images/150kgms/1.png",
      "./images/150kgms/2.png",
    ],
  },
  "150kg/10gSS": {
    name: "100kg/10g SS",
    "Brand Name": "",
    Type: "SS",
    Wheel: "না",
    Price: 10,
    Specification: [],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/40kg/main.png",
    "number sold": 10000,
    "other pic path": [
      "./images/150kgss/1.png",
      "./images/150kgss/2.png",
    ],
  },

  "250kg/20gMS": {
    name: "250kg/20g MS",
    "Brand Name": "",
    Type: "MS",
    Wheel: "না",
    Price: 10,
    Specification: [],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/40kg/main.png",
    "number sold": 10,
    "other pic path": [
      "./images/250kgms/1.png",
      "./images/250kgms/2.png",
    ],
  },
  "250kg/20gSS": {
    name: "250kg/20g SS",
    "Brand Name": "",
    Type: "SS",
    Wheel: "না",
    Price: 10,
    Specification: [],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/40kg/main.png",
    "number sold": 10,
    "other pic path": [
      "./images/250kgss/1.png",
      "./images/250kgss/2.png",
    ],
  },

  "300kg/20gMS": {
    name: "300kg/20g MS",
    "Brand Name": "GRAMEEN ROCKET",
    Type: "MS",
    Wheel: "হ্যাঁ",
    Price: 10,
    Specification: [
      "*৩০০ কেজি প্ল্যাটফর্ম স্কেল",
      "*আকার: ৪৫*৬০ সেমি",
      "*৪ভি ৪এ ৪৫০গ্রাম ব্যাটারি",
      "*স্টিল কিপ্যাড ডিজিটাল ডুয়াল ডিসপ্লে",
      "*ওজন পরিমাপ প্যানের পুরুত্ব ১.৮ মিমি",
      "*আই-আকৃতির বেড়ার উচ্চতা ৬৫ সেমি",
      "*মাথার উচ্চতা ৯১ সেমি",
      "*৮০০ কেজি সেন্সর প্যাকেজ",
      "*রঙিন ছবি মডেল",
      "*চাকা সহ",
      "আকার: ৯৯*৪৬*২৩.৫ সেমি",
      "গ্রস ওজন/নেট ওজন: ২৬ কেজি/২৫ কেজি",
    ],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/300kgms/main.png",
    "number sold": 1000,
    "other pic path": [
      "./images/300kgms/1.png",
      "./images/300kgms/2.png",
      "./images/300kgms/3.png",
    ],
  },

  "500kg/50gMS": {
    name: "500kg/50g MS",
    "Brand Name": "",
    Type: "MS",
    Wheel: "হ্যাঁ",
    Price: 10,
    Specification: [],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/40kg/main.png",
    "number sold": 10,
    "other pic path": [
      "./images/500kgms/1.png",
      "./images/500kgms/2.png",
      "./images/500kgms/3.png",
    ],
  },
  "500kg/50gSS": {
    name: "500kg/50g SS",
    "Brand Name": "",
    Type: "SS",
    Wheel: "হ্যাঁ",
    Price: 10,
    Specification: [],
    Category: "প্ল্যাটফর্ম স্কেল",
    "Picture Path": "./images/40kg/main.png",
    "number sold": 10,
    "other pic path": [
      "./images/500kgss/1.png",
      "./images/500kgss/2.png",
      "./images/500kgss/3.png",
    ],
  },
};
